// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Production [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5wCLBCEUPJKaw3lfUTEBPmAdkFhPlSyg',
    appId: '1:428730730000:web:78719cff10d4f913d9ac95',
    messagingSenderId: '428730730000',
    projectId: 'allergy-ident-prod',
    authDomain: 'allergy-ident-prod.firebaseapp.com',
    storageBucket: 'allergy-ident-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMj40iZdaq9BftfWtmWs-lXsp8T_ALXXs',
    appId: '1:428730730000:android:3d2827af37e3fdb1d9ac95',
    messagingSenderId: '428730730000',
    projectId: 'allergy-ident-prod',
    storageBucket: 'allergy-ident-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcW7CpWVc5OX1wMIid38T879RJESVAXxQ',
    appId: '1:428730730000:ios:4b5afbe7140113afd9ac95',
    messagingSenderId: '428730730000',
    projectId: 'allergy-ident-prod',
    storageBucket: 'allergy-ident-prod.firebasestorage.app',
    iosBundleId: 'com.example.flutterAllergyIdentifier',
  );
}
