// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Development [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZKiuR76DMtQj7FxGvdZF0mc9t_h0Tis',
    appId: '1:924105642469:web:5a88aa89910079bacc9f0c',
    messagingSenderId: '924105642469',
    projectId: 'allergy-ident-dev',
    authDomain: 'allergy-ident-dev.firebaseapp.com',
    storageBucket: 'allergy-ident-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BjWNgiXYMsyNIvbhZv0lWX6Iqr_yHaw',
    appId: '1:924105642469:android:91398bd22a357f8ccc9f0c',
    messagingSenderId: '924105642469',
    projectId: 'allergy-ident-dev',
    storageBucket: 'allergy-ident-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMmreMezfENopxbSOOa-izL_-6F14wuY',
    appId: '1:924105642469:ios:94647ae2471054b3cc9f0c',
    messagingSenderId: '924105642469',
    projectId: 'allergy-ident-dev',
    storageBucket: 'allergy-ident-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterAllergyIdentifier',
  );
}
